version: "2"

formatters:
  enable:
    - goimports

  settings:
    goimports:
      local-prefixes:
        - github.com/gocql/gocql
        - github.com/apache/cassandra-gocql-driver
        - github.com/apache/cassandra-gocql-driver/v2
    golines:
      max-len: 120

linters:
  exclusions:
    rules:
      - path: '(.+)_test\.go'
        text: "fieldalignment"
        linters:
          - govet

  default: none
  enable:
    - nolintlint
    - govet
  settings:
    govet:
      enable-all: true
      disable:
        - shadow

    nolintlint:
      allow-no-explanation: [ golines ]
      require-explanation: true
      require-specific: true

run:
  build-tags:
    - integration
    - unit