name: "Docs / Build PR"
# For more information,
# see https://sphinx-theme.scylladb.com/stable/deployment/production.html#available-workflows

on:
  push:
    paths:
      - "docs/**"
      - ".github/workflows/docs-pr.yml"
      - ".github/workflows/docs.yml"
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "docs/**"
      - ".github/workflows/docs-pr.yml"
      - ".github/workflows/docs.yml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/docs.yml
    with:
      target: ${{ github.sha }}
      publish: false
