name: Trigger jenkins job with custom scylla-bench image

on:
  pull_request_target:
    types: [opened, synchronize, reopened, labeled]

jobs:
  authorize:
    environment:
      ${{ github.event_name == 'pull_request_target' &&
      github.event.pull_request.head.repo.full_name != github.repository &&
      'default' || 'internal' }}
    runs-on: ubuntu-latest
    steps:
      - run: true

  build-scylla-bench:
    if: contains(github.event.pull_request.labels.*.name, 'extended-ci')
    needs: authorize
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Check out the scylla-bench repository
        uses: actions/checkout@v2
        with:
          repository: scylladb/scylla-bench
          path: scylla-bench

      - name: Checkout GoCQL PR Repository
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          path: gocql

      - name: Replace gocql with the PR version
        run: |
          cd scylla-bench
          go mod edit -replace github.com/gocql/gocql=../gocql
          go mod tidy

      - name: Build and push Scylla-bench Docker Image
        run: |
          cd scylla-bench
          export SCYLLA_BENCH_VERSION=tags/v0.1.22
          export NAME="${{ github.event.pull_request.head.ref }}"
          export SCYLLA_BENCH_DOCKER_IMAGE=scylladb/gocql-extended-ci:scylla-bench-${NAME}
          docker build -f ../gocql/.github/workflows/Dockerfile . -t ${SCYLLA_BENCH_DOCKER_IMAGE} --build-arg version=$SCYLLA_BENCH_VERSION
          docker push ${SCYLLA_BENCH_DOCKER_IMAGE}

      - name: Start Jenkins job
        uses: sylwiaszunejko/jenkins_client@main
        with:
          jenkins_job_name: 'scylla-staging/sylwia.szunejko/longevity-large-partition-asymmetric-cluster-3h-test'
          jenkins_job_parameters: '{"email_recipients": "sylwia.szunejko@scylladb.com", "scylla_version": "master:latest", "extra_environment_variables": "SCT_STRESS_IMAGE.scylla-bench=scylladb/gocql-extended-ci:scylla-bench-${{ github.event.pull_request.head.ref }}"}'
          jenkins_base_url: 'https://jenkins.scylladb.com/'
          jenkins_user: sylwiaszunejko
          jenkins_password: ${{ secrets.JENKINS_TOKEN }}
          wait_for_result: 'True'
          polling_interval: '120'
          polling_timeout: '12600'
