name: Build

on:
  push:
    branches: [master]
    paths-ignore:
      - "**.md"
      - "docs/**"
      - .github/workflows/docs-*
      - .github/workflows/bench-tests.yml
      - .github/workflows/extended-ci-longevity-large-partitions-with-network-nemesis-1h-test.yml

permissions:
  contents: read

jobs:
  build:
    name: Build master
    uses: ./.github/workflows/build.yml
    with:
      target_commit: ${{ github.sha }}
      arch: amd64
