name: Build

on:
  push:
    branches:
      - master
    paths-ignore:
      - "*.md"
      - "docs/**"
      - .github/workflows/docs-*
      - .github/workflows/bench-tests.yml
      - .github/workflows/extended-ci-longevity-large-partitions-with-network-nemesis-1h-test.yml
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - "*.md"
      - "docs/**"
      - .github/workflows/docs-*
      - .github/workflows/bench-tests.yml
      - .github/workflows/extended-ci-longevity-large-partitions-with-network-nemesis-1h-test.yml

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/cache@v4
        with:
          path: |
            /home/runner/.cache/pip
            /home/runner/.ccm/scylla-repository
            /home/runner/.ccm/repository
            /home/runner/.sdkman
            testdata/pki
            bin/
          # CCM, scylla, cassandra and java versions are in Makefile
          key: pr-check-${{ runner.os }}-${{ hashFiles('Makefile') }}

      - uses: actions/setup-go@v6
        with:
          cache-dependency-path: |
            lz4/go.sum
            tests/bench/go.sum
            go.sum

      - name: Run linters
        run: make check

      - name: Run unit tests
        run: make test-unit

      - run: sudo sh -c "echo 2097152 >> /proc/sys/fs/aio-max-nr"

      - name: Run integration suite
        run: make test-integration-scylla

      - name: Run CCM integration suite
        run: TEST_INTEGRATION_TAGS="ccm gocql_debug" make test-integration-scylla

