name: Build

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      SCYLLA_IMAGE: scylladb/scylla:5.4.6
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
      - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        id: gomod-cache
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('go.mod') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - run: go vet ./...

      - name: Run unit tests
        run: go test -tags unit -race ./...

      - name: Install Docker compose
        env:
          DOCKER_COMPOSE_VERSION: 2.20.0
        run: sudo curl -L "https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

      - run: sudo sh -c "echo 2097152 >> /proc/sys/fs/aio-max-nr"
      - run: ./integration.sh cassandra scylla
      - run: ./integration.sh integration scylla
      - run: ./integration.sh ccm
      - run: ./integration.sh tablet
